# Generated by Django 3.2.7 on 2021-09-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210916_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
